import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import Link from 'next/link';
import styles from './page.module.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"d-flex justify-content-center align-items-center " + inter.className}>
        <div className='d-grid'>
          <div className='d-flex justify-content-between'>
            <Link href='/counter'>Counter</Link>
            <Link href='/task-list'>Task List</Link>
            <Link href='/event-listener'>Event Listeners</Link>
            <Link href='/manipulate-numbers'>Manipulate Numbers</Link>
          </div>
          <div className={'d-flex justify-content-center m-3 ' + styles.container}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
